# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RPS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RPS

pod 'ReSwift'
  target 'RPSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RPSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
